### ISSUE TITLE
Initia.js is not supported in the browser environment

### ISSUE THREAD

**Issue by Simonpedro** [initia-labs/initia.js#77]
**Expected behavior**

I'd expect to be able to use LCDClient in the browser.

```js
import { LCDClient } from "@initia/initia.js"
```

**Actual behavior**

When doing:

```js
import { LCDClient } from "@initia/initia.js"
```

It fails with:
```sh
ReferenceError: Buffer is not defined
    at node_modules/@initia/initia.js/dist/core/PublicKey.js
```

Given that `Buffer` is not part of the Web API

**To reproduce**

Import LCDClient in the browser.

**System information**

@initia/initia.js@0.2.9

Tested in latest Chrome

**Comment by simcheolhwan** [comment]
This library uses `Buffer`, so we are aware that it currently can't be used in web browser-based projects without a polyfill. While resolving this issue is on our roadmap, it's not our highest priority at the moment. In the meantime, please choose one of the following options:

### 1. Polyfill `Buffer` in your frontend project.

How to do this:
If you're using [Vite](https://vitejs.dev/), configure `vite.config.js` as follows. Alternatively, there are many examples available online that you can refer to.

```js
import { nodePolyfills } from "vite-plugin-node-polyfills"

export default defineConfig({
  plugins: [react(), nodePolyfills()],
})
```

If you're using [Create React App](https://create-react-app.dev/), you can find plenty of examples online that suggest using `react-app-rewired` instead of `react-scripts` to resolve this issue.

### 2. Instead of using this library, use [@initia/initia.proto](https://www.npmjs.com/package/@initia/initia.proto) directly and use [cosmjs](https://github.com/cosmos/cosmjs), etc.

For example, you can change the following code

```js
import { MsgExecute } from "@initia/initia.js"

const msgs = [
  new MsgExecute(
    address,
    "0x1",
    "dex",
    "swap_script",
    [],
    [
      bcs.address().serialize("0x").toBytes(),
      bcs.address().serialize("0x").toBytes(),
      bcs.u64().serialize("1000000").toBytes(),
      bcs.option(bcs.u64()).serialize(null).toBytes(),
    ]
  ),
]
```

to this code.

```js
import { MsgExecute } from "@initia/initia.proto/initia/move/v1/tx"

const messages = [
  {
    typeUrl: "/initia.move.v1.MsgExecute",
    value: MsgExecute.fromPartial({
      sender: address,
      moduleAddress: "0x1",
      moduleName: "dex",
      functionName: "swap_script",
      typeArgs: [],
      args: [
        bcs.address().serialize("0x").toBytes(),
        bcs.address().serialize("0x").toBytes(),
        bcs.u64().serialize("1000000").toBytes(),
        bcs.option(bcs.u64()).serialize(null).toBytes(),
      ],
    }),
  },
]
```

Let me know if you have any further questions.

**Comment by Simonpedro** [comment]
I ended up using the polyfill to square away the issue for now. Thank you!

**Comment by Vritra4** [comment]
closing this: please feel free to raise another issue if you have another question!
